<<<<<<< HEAD
name: Build Docker
=======
name: Build and Publish Docker
>>>>>>> adding docker build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
<<<<<<< HEAD
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: brucewillke/airconnect
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
=======
>>>>>>> adding docker build
