name: Build Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: myrepo/Publish-Docker-Github-Action@master
      with:
        name: myrepo/docker-githubaction
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
